en = {
    'start.default': 'You are ready to use CAT service.',
    # HTML
    'setting.default': '\n'.join([
        '<b><u>STATUS</u></b>',
        '',
        '<b>Rise Alert</b>: {rise_alert}',
        '<b>RG Exception List</b>: {rg_exception_list}'
    ]),
    'setting.rise_alert': 'Set Rise Alert',
    'setting.rg_exception': 'Set RG Exception List',
    'setting.back': 'Back to Setting',
    'rise_alert.default.active': '<b>Current Status</b>: ACTIVE',
    'rise_alert.default.inactive': '<b>Current Status</b>: INACTIVE',
    'rise_alert.activate': 'Activate',
    'rise_alert.deactivate': 'Deactivate',
    'rg_exception.default': '<b>RG Exception List</b>: {list}',
    'rg_exception.add': 'Add to the list',
    'rg_exception.remove': 'Remove from the list',
    'com.success': 'Success',
    'com.active': 'ACTIVE',
    'com.inactive': 'INACTIVE',
    'com.exit': 'Exit',
    'com.retry': 'Retry',
    'com.error': 'Error: {description}',
    'action.default': 'Choose Your Action',
    'action.buy': 'Buy',
    'action.sell': 'Sell',
    'action.rg': 'Random Game',
    'action.buy.pg_text': 'Total: {total}\nCurrent Page: {page}',
    'action.sell.pg_text': 'Total: {total}\nCurrent Page: {page}',
    'action.buy_input_text': 'Order Type: <b>buy</b>\nSelected Ticker: <i>{ticker}</i>\n\nEnter the amount that you want to buy in KRW',
    'action.sell_input_text': 'Order Type: <b>sell</b>\nSelected Ticker: <i>{ticker}</i>\nCurrent Balance: {curr_balance}\nCalculated Value: {calculated_value}\n\nEnter the amount that you want to sell',
    'action.rg_input_text': 'Order Type: <b>Random Game</b>\n\nEnter the number of coins and the amount for each coin',
    'action.rg_input_ph': '[number of coins] [price]',
    'buy.success': 'Buy {ticker}: Success',
    'buy.fail': 'Buy {ticker}: Fail',
    'sell.success': 'Sell {ticker}: Success',
    'ws.rise_alert': '{ticker} exceeded {intr}%.',
    'ws.sell': 'Sell Now',
    'ws.ignore': 'Ignore',
}
